default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  owner: educacao
  username: educacao
  password: educacao
  template: template0

development:
  <<: *default
  database: educacao_development

test:
  <<: *default
  database: educacao_test
