navigation:
  - ***REMOVED***:
      type: "dashboard"
      icon: "fa-home"
      path: "root_path"
  - ***REMOVED***:
      type: "accounts"
      icon: "fa-user"
      path: "edit_account_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-envelope-o"
      path: "new_contact_school_path"
  - ***REMOVED***:
      type: "disciplinary_incidents"
      icon: "fa-bar-chart-o"
      path: "disciplinary_incidents_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-graduation-cap"
      path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-cutlery"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***s"
            path: "***REMOVED***s_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "configurations"
      icon: "fa-cog"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "roles"
            path: "roles_path"
        - ***REMOVED***:
            type: "unities"
            path: "unities_path"
        - ***REMOVED***:
            type: "users"
            path: "users_path"
        - ***REMOVED***:
            type: "general_configurations"
            path: "edit_general_configurations_path"
        - ***REMOVED***:
            type: "ieducar_api_configurations"
            path: "edit_ieducar_api_configurations_path"
        - ***REMOVED***:
           type: "***REMOVED***"
           path: "edit_notification_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-bullhorn"
      path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-exchange"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***_classes"
            path: "***REMOVED***_classes_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "moved_***REMOVED***"
            path: "moved_***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-retweet"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "authorization_***REMOVED***"
            path: "authorization_***REMOVED***_path"
