navigation:
  - ***REMOVED***:
      type: "dashboard"
      icon: "fa-home"
      path: "root_path"
      visible: true
  - ***REMOVED***:
      type: "messages"
      icon: "fa-inbox"
      path: "messages_path"
      visible: true
  - ***REMOVED***:
      type: "accounts"
      icon: "fa-user"
      path: "edit_account_path"
      visible: true
  - ***REMOVED***:
      type: "current_role"
      icon: "fa-cogs"
      path: "current_roles_path"
      visible: true
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-envelope-o"
      path: "new_contact_school_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-ticket"
      sub***REMOVED***s:
          - ***REMOVED***:
              type: "***REMOVED***s"
              path: "***REMOVED***s_path"
          - ***REMOVED***:
              type: "***REMOVED***_confirmations"
              path: "***REMOVED***_confirmations_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-bar-chart-o"
      path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-graduation-cap"
      path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-cutlery"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***s"
            path: "***REMOVED***s_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "configurations"
      icon: "fa-cog"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "roles"
            path: "roles_path"
        - ***REMOVED***:
            type: "unities"
            path: "unities_path"
        - ***REMOVED***:
            type: "users"
            path: "users_path"
        - ***REMOVED***:
            type: "general_configurations"
            path: "edit_general_configurations_path"
        - ***REMOVED***:
            type: "ieducar_api_configurations"
            path: "edit_ieducar_api_configurations_path"
        - ***REMOVED***:
           type: "***REMOVED***"
           path: "edit_notification_path"
        - ***REMOVED***:
            type: "***REMOVED***_configs"
            path: "edit_***REMOVED***_configs_path"
        - ***REMOVED***:
            type: "entity_configurations"
            path: "edit_entity_configurations_path"
        - ***REMOVED***:
            type: "test_settings"
            path: "test_settings_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-bullhorn"
      path: "***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-exchange"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***_classes"
            path: "***REMOVED***_classes_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "moved_***REMOVED***"
            path: "moved_***REMOVED***_path"
  - ***REMOVED***:
      type: "***REMOVED***"
      icon: "fa-retweet"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "authorization_***REMOVED***"
            path: "authorization_***REMOVED***_path"
  - ***REMOVED***:
      type: "school_calendars"
      icon: "fa-calendar"
      path: "school_calendars_path"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "school_calendar_events"
            visible: "only-when-active"
  - ***REMOVED***:
      type: "teaching_plans"
      icon: "fa-book"
      path: "teaching_plans_path"
  - ***REMOVED***:
      type: "lesson_plans_***REMOVED***"
      icon: "fa-pencil"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "discipline_lesson_plans"
            path: "discipline_lesson_plans_path"
        - ***REMOVED***:
            type: "knowledge_area_lesson_plans"
            path: "knowledge_area_lesson_plans_path"
  - ***REMOVED***:
      type: "avaliations_***REMOVED***"
      icon: "fa-file-text-o"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "conceptual_exams"
            path: "new_conceptual_exam_path"
        - ***REMOVED***:
            type: "descriptive_exams"
            path: "new_descriptive_exam_path"
        - ***REMOVED***:
            type: "avaliations"
            path: "avaliations_path"
        - ***REMOVED***:
            type: "daily_notes"
            path: "new_daily_note_path"
  - ***REMOVED***:
      type: "recovery_diary_records_***REMOVED***"
      icon: "fa-file-text"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "school_term_recovery_diary_records"
            path: "school_term_recovery_diary_records_path"        
  - ***REMOVED***:
      type: "frequencies_***REMOVED***"
      icon: "fa-check-square-o"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "daily_frequencies"
            path: "new_daily_frequency_path"
        - ***REMOVED***:
            type: "absence_justifications"
            path: "absence_justifications_path"
  - ***REMOVED***:
      type: "reports"
      icon: "fa-files-o"
      sub***REMOVED***s:
        - ***REMOVED***:
            type: "exam_record_report"
            path: "exam_record_report_path"
        - ***REMOVED***:
            type: "***REMOVED***"
            path: "***REMOVED***_path"
        - ***REMOVED***:
            type: "lesson_plan_report"
            path: "lesson_plan_report_path"
        - ***REMOVED***:
            type: "attendance_record_report"
            path: "attendance_record_report_path"
  - ***REMOVED***:
      type: "ieducar_api_exam_postings"
      icon: "fa-arrow-circle-up"
      path: "ieducar_api_exam_postings_path"
